packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  convex: ^1.31.2
  better-auth: 1.4.18
  '@convex-dev/better-auth': ^0.10.10
  react: ^19.2.4
  react-dom: ^19.2.4
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
