/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ITokenRouteImport } from './routes/i/$token'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices/new'
import { Route as AppClientsNewRouteImport } from './routes/_app/clients/new'
import { Route as AppClientsIdRouteImport } from './routes/_app/clients/$id'
import { Route as AppInvoicesIdIndexRouteImport } from './routes/_app/invoices/$id/index'
import { Route as AppInvoicesIdEditRouteImport } from './routes/_app/invoices/$id/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdIndexRoute = AppInvoicesIdIndexRouteImport.update({
  id: '/invoices/$id/',
  path: '/invoices/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdEditRoute = AppInvoicesIdEditRouteImport.update({
  id: '/invoices/$id/edit',
  path: '/invoices/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AppLoginRoute
  '/settings': typeof AppSettingsRoute
  '/signup': typeof AppSignupRoute
  '/i/$token': typeof ITokenRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/clients/': typeof AppClientsIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/invoices/$id/edit': typeof AppInvoicesIdEditRoute
  '/invoices/$id/': typeof AppInvoicesIdIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AppLoginRoute
  '/settings': typeof AppSettingsRoute
  '/signup': typeof AppSignupRoute
  '/i/$token': typeof ITokenRoute
  '/': typeof AppIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/clients': typeof AppClientsIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/invoices/$id/edit': typeof AppInvoicesIdEditRoute
  '/invoices/$id': typeof AppInvoicesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/signup': typeof AppSignupRoute
  '/i/$token': typeof ITokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/invoices/$id/edit': typeof AppInvoicesIdEditRoute
  '/_app/invoices/$id/': typeof AppInvoicesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/signup'
    | '/i/$token'
    | '/clients/$id'
    | '/clients/new'
    | '/invoices/new'
    | '/clients/'
    | '/invoices/'
    | '/invoices/$id/edit'
    | '/invoices/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/signup'
    | '/i/$token'
    | '/'
    | '/clients/$id'
    | '/clients/new'
    | '/invoices/new'
    | '/clients'
    | '/invoices'
    | '/invoices/$id/edit'
    | '/invoices/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/login'
    | '/_app/settings'
    | '/_app/signup'
    | '/i/$token'
    | '/_app/'
    | '/_app/clients/$id'
    | '/_app/clients/new'
    | '/_app/invoices/new'
    | '/_app/clients/'
    | '/_app/invoices/'
    | '/_app/invoices/$id/edit'
    | '/_app/invoices/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ITokenRoute: typeof ITokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id/': {
      id: '/_app/invoices/$id/'
      path: '/invoices/$id'
      fullPath: '/invoices/$id/'
      preLoaderRoute: typeof AppInvoicesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id/edit': {
      id: '/_app/invoices/$id/edit'
      path: '/invoices/$id/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof AppInvoicesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLoginRoute: typeof AppLoginRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignupRoute: typeof AppSignupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppInvoicesIdEditRoute: typeof AppInvoicesIdEditRoute
  AppInvoicesIdIndexRoute: typeof AppInvoicesIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLoginRoute: AppLoginRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignupRoute: AppSignupRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppInvoicesIdEditRoute: AppInvoicesIdEditRoute,
  AppInvoicesIdIndexRoute: AppInvoicesIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ITokenRoute: ITokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
